version: '3.3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=contrasenia
      - MYSQL_DATABASE=saheya-v01
      - MYSQL_PORT=3306
    ports:
      - 3005:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3002:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=contrasenia
